apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: scotel-price
  name: price-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: scotel-price
status:
  loadBalancer: {}