apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: scotel-product
  name: product-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: scotel-product
  1 apiVersion: v1
status:
  loadBalancer: {}