name: Variables and Conditions

on:
  workflow_dispatch: 
    inputs:
      labName:
        description: One or Two
        required: true
        type: boolean
        default: true

jobs:

  do-stuff:
    runs-on: ubuntu-latest
    steps:
    - name: Echo One
      if: ${{ github.event.inputs.labName == false}}
      run: | 
        echo "Hello, One!"

    - name: Echo Two
      if: ${{ github.event.inputs.labName == true}}
      run: | 
        echo "Hello, Two!"