name: Variables and Conditions

on:
  workflow_dispatch: 
    inputs:
      one:
        description: One
        required: true
        type: boolean
        default: true
      two:
        description: Two
        required: true
        type: boolean
        default: true
      three:
        description: Three
        required: true
        type: boolean
        default: true

jobs:

  do-stuff:
    runs-on: ubuntu-latest
    steps:
    - name: Echo One
      if: ${{ github.event.inputs.one}}
      run: | 
        echo "Hello, One! ${{ github.event.inputs.one}}"

    - name: Echo One More
      if: ${{ !github.event.inputs.one }}
      run: | 
        echo "Hello, One! ${{ github.event.inputs.one}}"

    - name: Echo always one More
      if: always()
      run: | 
        echo "Hello, One! ${{ github.event.inputs.one}}"

    - name: Echo Another One
      if: ${{ github.event.inputs.one == 'true'}}
      run: | 
        echo "Hello, One! ${{ github.event.inputs.one}}"

    - name: Echo Two
      if: ${{ github.event.inputs.two == 'true'}}
      run: | 
        echo "Hello, Two!"

    - name: Echo Three
      run: | 
        echo "Hello, Three! X"