name: nginx Ingress

on:
  workflow_dispatch: 
    inputs:
      k8sName:
        description: k8sname
        required: true
        type: string
        default: 'abc'

      argocd:
        description: ArgoCD
        required: true
        type: boolean
        default: false
      
      hubble:
        description: Cilium Hubble
        required: true
        type: boolean
        default: true

      cilium:
        description: Cilium Grafana
        required: true
        type: boolean
        default: false

      testkube:
        description: Testkube
        required: true
        type: boolean
        default: true

      otel:
        description: OpenTelemetry
        required: true
        type: boolean
        default: true

      dqualizer:
        description: dqualizer
        required: true
        type: boolean
        default: false

      ocelot:
        description: ocelot
        required: true
        type: boolean
        default: false

jobs: 
  configure-ingress:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: | 
        echo "Hello, Welt!"
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Display az cli version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - name: Get Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: mhsrg-${{ github.event.inputs.k8sName }}
        cluster-name: mhs-${{ github.event.inputs.k8sName }}

    - name: Configure ArgoCD
      if: ${{ github.event.inputs.argocd }}
      continue-on-error: true
      run: |
        echo not yet solved

    - name: Configure Istio Stuff
      if: ${{ github.event.inputs.istio }}
      continue-on-error: true
      run: |

        export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        export INGRESS_DOMAIN=${INGRESS_HOST}.nip.io

        

    - name: Configure Hubble Stuff
      if: ${{ github.event.inputs.hubble }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: hubble-ui
          namespace: kube-system
        spec:
          ingressClassName: nginx
          rules:
            - host: hubble.${INGRESS_IP}.nip.io
              http:
                paths:
                  - pathType: Prefix
                    backend:
                      service:
                        name: hubble-ui
                        port:
                          number: 80
                    path: /
        ---
        EOF

    - name: Configure Otel Stuff
      if: ${{ github.event.inputs.otel }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: otel
          namespace: otel
        spec:
          ingressClassName: nginx
          rules:
            - host: otel.${INGRESS_IP}.nip.io
              http:
                paths:
                  - pathType: Prefix
                    backend:
                      service:
                        name: my-otel-demo-tmp-frontendproxy
                        port:
                          number: 80
                    path: /
        ---
        EOF


    - name: Configure Kubetest Stuff
      if: ${{ github.event.inputs.otel }}
      continue-on-error: true
      run: |

        export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        export INGRESS_DOMAIN=${INGRESS_HOST}.nip.io

        cat <<EOF | kubectl apply -f -
        apiVersion: networking.istio.io/v1alpha3
        kind: Gateway
        metadata:
          name: testkube-gateway
          namespace: istio-system
        spec:
          selector:
            istio: ingressgateway
          servers:
          - port:
              number: 80
              name: http-k8stestkube
              protocol: HTTP
            hosts:
            - "testkube.${INGRESS_DOMAIN}"
        ---
        apiVersion: networking.istio.io/v1alpha3
        kind: VirtualService
        metadata:
          name: testkube-vs
          namespace: istio-system
        spec:
          hosts:
          - "testkube.${INGRESS_DOMAIN}"
          gateways:
          - testkube-gateway
          http:
          - route:
            - destination:
                host: testkube-dashboard.testkube.svc.cluster.local
                port:
                  number: 8080
        ---
        apiVersion: networking.istio.io/v1alpha3
        kind: DestinationRule
        metadata:
          name: testkube
          namespace: istio-system
        spec:
          host: testkube-dashboard.testkube
          trafficPolicy:
            tls:
              mode: DISABLE
        ---
        EOF


    - name: Bill of materials
      continue-on-error: true
      run: |

        export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        export INGRESS_DOMAIN=${INGRESS_HOST}.nip.io
        
        echo Ingress Host: $INGRESS_DOMAIN Ingress Domain: $INGRESS_DOMAIN
        
        echo http://kiali.${INGRESS_DOMAIN}
        echo http://hubble.${INGRESS_DOMAIN}
        echo http://grafana.${INGRESS_DOMAIN}
        echo http://testkube.${INGRESS_DOMAIN}
        echo http://tracing.${INGRESS_DOMAIN}
        echo http://otel.${INGRESS_DOMAIN}


        kubectl get svc argocd-server -n argocd
        