name: nginx Ingress

on:
  workflow_dispatch: 
    inputs:
      k8sName:
        description: k8sname
        required: true
        type: string
        default: 'abc'

      headlamp:
        description: headlamp
        required: true
        type: boolean
        default: true

      skooner:
        description: skooner
        required: true
        type: boolean
        default: false

      argocd:
        description: ArgoCD
        required: true
        type: boolean
        default: false
      
      hubble:
        description: Cilium Hubble
        required: true
        type: boolean
        default: false

      cilium:
        description: Cilium Grafana
        required: true
        type: boolean
        default: false

      testkube:
        description: Testkube
        required: true
        type: boolean
        default: false

      otel:
        description: OpenTelemetry
        required: true
        type: boolean
        default: false

      todoapp:
        description: TodoApp
        required: true
        type: booelan
        default: false

      ocelot:
        description: ocelot
        required: true
        type: boolean
        default: false

jobs: 
  configure-ingress:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: | 
        echo "Hello, Welt!"
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Display az cli version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - name: Get Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: mhsrg-${{ github.event.inputs.k8sName }}
        cluster-name: mhs-${{ github.event.inputs.k8sName }}

    - name: Configure ArgoCD
      if: ${{ github.event.inputs.argocd }}
      continue-on-error: true
      run: |
        echo not yet solved

    - name: Configure Istio Stuff
      if: ${{ github.event.inputs.istio }}
      continue-on-error: true
      run: |

        export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        export INGRESS_DOMAIN=${INGRESS_HOST}.nip.io

    - name: Configure Headlamp Stuff
      if: ${{ github.event.inputs.headlamp }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        kind: Ingress
        apiVersion: networking.k8s.io/v1
        metadata:
          name: headlamp
          namespace: kube-system
        spec:
          ingressClassName: nginx
          rules:
            - host: headlamp.${INGRESS_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: headlamp
                        port:
                          number: 80
                    pathType: ImplementationSpecific
        ---
        EOF
        
    - name: Configure Skooner Stuff
      if: ${{ github.event.inputs.skooner }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        kind: Ingress
        apiVersion: networking.k8s.io/v1
        metadata:
          name: skooner
          namespace: kube-system
        spec:
          ingressClassName: nginx
          rules:
            - host: skooner.${INGRESS_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: skooner
                        port:
                          number: 80
                    pathType: ImplementationSpecific
        ---
        EOF

    - name: Configure Hubble Stuff
      if: ${{ github.event.inputs.hubble }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: hubble-ui
          namespace: kube-system
        spec:
          ingressClassName: nginx
          rules:
            - host: hubble.${INGRESS_DOMAIN}
              http:
                paths:
                  - pathType: Prefix
                    backend:
                      service:
                        name: hubble-ui
                        port:
                          number: 80
                    path: /
        ---
        EOF

    - name: Configure Otel Stuff
      if: ${{ github.event.inputs.otel }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: otel
          namespace: otel
        spec:
          ingressClassName: nginx
          rules:
            - host: otel.${INGRESS_DOMAIN}
              http:
                paths:
                  - pathType: Prefix
                    backend:
                      service:
                        name: oteldemo-frontendproxy.otel.svc.cluster.local
                        port:
                          number: 8080
                    path: /
        ---
        EOF

    - name: Configure Petclinic Stuff
      if: ${{ github.event.inputs.petclinic }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        kind: Ingress
        apiVersion: networking.k8s.io/v1
        metadata:
          name: petclinic
          namespace: spring-petclinic
        spec:
          ingressClassName: nginx
          rules:
            - host: petclinic.${INGRESS_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: api-gateway.spring-petclinic.svc.cluster.local
                        port:
                          number: 80
                    pathType: ImplementationSpecific
        ---
        EOF

    - name: Configure Todo App Stuff
      if: ${{ github.event.inputs.todoapp }}
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io

        cat <<EOF | kubectl apply -f -
        kind: Ingress
        apiVersion: networking.k8s.io/v1
        metadata:
          name: todoapp
          namespace: todoapp
        spec:
          ingressClassName: nginx
          rules:
            - host: todoui.${INGRESS_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: todoui.todoapp
                        port:
                          number: 8090
                    pathType: ImplementationSpecific
        ---
        EOF

    - name: Bill of materials
      continue-on-error: true
      run: |

        export INGRESS_IP=$(kubectl get service --namespace ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[].ip}')
        echo $INGRESS_IP
        export INGRESS_DOMAIN=${INGRESS_IP}.nip.io       
        echo Ingress Host: $INGRESS_DOMAIN Ingress Domain: $INGRESS_DOMAIN

        echo ${{ github.event.inputs.headlamp }}

        echo http://headlamp.${INGRESS_DOMAIN}
        echo http://skooner.${INGRESS_DOMAIN}        
        echo http://hubble.${INGRESS_DOMAIN}
        echo http://otel.${INGRESS_DOMAIN}
        echo http://petclinic.${INGRESS_DOMAIN}

        kubectl get svc argocd-server -n argocd
        
