name: Deploy AKS

on:
  workflow_dispatch: 
    inputs:
      labName:
        description: Labname
        required: true
        type: string
        default: 'abc'

      nodeCount:
        description: Nodecount
        required: true
        type: string
        default: '1'

jobs: 
  echo-something:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: | 
        echo "Hello, Welt!"
        echo ${{ github.event.inputs.nodeCount }}
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az group list
          echo az group create mhs-${{ github.event.inputs.nodeCount }}
          echo az aks create --resource-group mhsdemo --name mhs-${{ github.event.inputs.labName }} --node-count 3 --node-vm-size Standard_E8_v3 --generate-ssh-keys
          
    
