name: Deploy AKS

on:
  workflow_dispatch: 
    inputs:
      labName:
        description: Labname
        required: true
        type: string

      nodeCount:
        description: Nodecount
        required: true
        type: string

jobs: 
  echo-something:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: | 
        echo "Hello, Welt!"
        echo ${{ github.event.inputs.nodeCount }}
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az group list
          echo az group create mhs-${{ github.event.inputs.nodeCount }}
        
  
