name: Apps - Deploy demos on AKS

on:
  workflow_dispatch: 
    inputs:
      k8sName:
        description: k8sname
        required: true
        type: string
        #default: 'abc'

      otel:
        description: OpenTelemetry
        required: true
        type: boolean
        default: false

      otel-istio:
        description: Enable OpenTelemetry for Istio
        required: true
        type: boolean
        default: false

      petclinic:
        description: Spring Petclinic
        required: true
        type: boolean
        default: false

      petclinic-istio:
        description: Enable Petclinic for Istio 
        required: true
        type: boolean
        default: false

      todoapp:
        description: Novatec TodoApp Sample
        required: true
        type: boolean
        default: true

      dqualizer:
        description: dqualizer
        required: true
        type: boolean
        default: false

      ocelot:
        description: ocelot
        required: true
        type: boolean
        default: false

jobs: 
  deploy-stuff-on-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: | 
        echo "Hello, Welt !"
      
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '${{ secrets.AZURE_PLAYGROUND }}'

    - name: Display az cli version
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az version

    - name: Get Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: mhsrg-${{ github.event.inputs.k8sName }}
        cluster-name: mhs-${{ github.event.inputs.k8sName }}

    - name: Enable OpenTelemetry Namespace for Istio
      if: ${{ github.event.inputs.otel-istio == 'true' }}
      continue-on-error: true
      run: |
        kubectl create namespace otel
        kubectl label namespace otel istio-injection=enabled --overwrite

    - name: Install OpenTelemetry Demo
      if: ${{ github.event.inputs.otel == 'true'}}
      continue-on-error: true
      run: |
        helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
        helm install oteldemo open-telemetry/opentelemetry-demo -n otel --create-namespace

    - name: Checkout Petclinic
      if: ${{ github.event.inputs.petclinic == 'true'}}
      uses: actions/checkout@v3
      with:
        repository: maeddes/spring-petclinic-cloud
        ref: 'master'
        path: './spring-petclinic-cloud'

    - name: Create Spring Petclinic Namespace
      if: ${{ github.event.inputs.petclinic == 'true' }}
      continue-on-error: true
      run: |
        kubectl create namespace spring-petclinic

    - name: Enable Spring Petclinic Namespace for Istio
      if: ${{ github.event.inputs.petclinic-istio == 'true' }}
      continue-on-error: true
      run: |
        kubectl label namespace spring-petclinic istio-injection=enabled --overwrite

    - name: Deploy Spring Petclinic 
      if: ${{ github.event.inputs.petclinic == 'true' }}
      continue-on-error: true
      run: |
        pwd
        ls -ltr
        kubectl apply -f spring-petclinic-cloud/argocd -n spring-petclinic

    - name: Expose Spring Petclinic via Istio Ingress
      if: ${{ github.event.inputs.petclinic-istio == 'true' }}
      continue-on-error: true
      run: |

        export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        export INGRESS_DOMAIN=${INGRESS_HOST}.nip.io

        cat <<EOF | kubectl apply -f -
        apiVersion: networking.istio.io/v1alpha3
        kind: Gateway
        metadata:
          name: petclinic-gateway
          namespace: istio-system
        spec:
          selector:
            istio: ingressgateway
          servers:
          - port:
              number: 80
              name: http-petclinic
              protocol: HTTP
            hosts:
            - "petclinic.${INGRESS_DOMAIN}"
        ---
        apiVersion: networking.istio.io/v1alpha3
        kind: VirtualService
        metadata:
          name: petclinic-vs
          namespace: istio-system
        spec:
          hosts:
          - "petclinic.${INGRESS_DOMAIN}"
          gateways:
          - petclinic-gateway
          http:
          - route:
            - destination:
                host: api-gateway.spring-petclinic.svc.cluster.local
                port:
                  number: 80
        ---
        apiVersion: networking.istio.io/v1alpha3
        kind: DestinationRule
        metadata:
          name: petclinic
          namespace: istio-system
        spec:
          host: api-gateway.spring-petclinic
          trafficPolicy:
            tls:
              mode: DISABLE
        ---
        EOF

    - name: Checkout Todo App
      if: ${{ github.event.inputs.todoapp == 'true'}}
      continue-on-error: true
      uses: actions/checkout@v3
      with:
        repository: maeddes/technologyconsulting-containerexerciseapp
        ref: 'master'
        path: './technologyconsulting-containerexerciseapp'

    - name: Polyglot Sample Todo Application
      if: ${{ github.event.inputs.todoapp == 'true'}}
      continue-on-error: true
      run: |
        echo create ns if not exists ..
        kubectl create namespace todoapp --dry-run=client -o yaml | kubectl apply -f -
        kubectl config set-context --current --namespace=todoapp
        cd technologyconsulting-containerexerciseapp
        pwd
        ls -ltr
        ./deployAll.sh

    - name: Bill of materials
      continue-on-error: true
      run: |
        export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        export INGRESS_DOMAIN=${INGRESS_HOST}.nip.io
        
        echo Ingress Host: $INGRESS_DOMAIN Ingress Domain: $INGRESS_DOMAIN
        
        echo http://petclinic.${INGRESS_DOMAIN}
        kubectl get svc api-gateway -n spring-petclinic