name: Deploy AKS

on:
  workflow_dispatch: {}

jobs: 
  echo-something:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Something
      run: echo "Hello, Welt!"
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
