name: Deploy AKS

on:
  workflow_dispatch: 
    inputs:
      k8sName:
        description: k8sname
        required: true
        type: string
        default: 'abc'

      nodeCount:
        description: Nodecount
        required: true
        type: string
        default: '1'

      cilium:
        description: Enable Cilium
        required: true
        type: boolean
        default: false

jobs: 
  deploy-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Something
      run: | 
        echo "Hello, Welt!"

      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Display az cli version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version
