name: Crash Test Dummy

on:
  workflow_dispatch: {}

jobs:
  destroy-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Test AZ CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version
