name: Crash Test Dummy

on:
  workflow_dispatch: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Test AZ CLI
      if: false
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az version

    - name: Cilium Install
      continue-on-error: true
      run: | 
        echo is the indentation
              echo important
                    echo in a run block?

