name: Crash Test Dummy

on:
  workflow_dispatch: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Test AZ CLI
      if: false
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - name: Cilium Install
      continue-on-error: true
      run: | 
        az version
        gcloud version

    - name: Install TestKube
      if: ${{ github.event.inputs.testkube }}
      continue-on-error: true
      run: |
        wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add - && echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt-get install -y testkube
        testkube init