name: Crash Test Dummy

on:
  workflow_dispatch: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Test AZ CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - name: Cilium Install
      continue-on-error: true
      run: | 
        az version

