name: Crash Test Dummy

on:
  workflow_dispatch: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Test AZ CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - name: Install Cilium
      uses: azure/CLI@v1
      with:
        inlineScript: |

          
          CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
          CLI_ARCH=amd64
          if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
          curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
          tar -xvf cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
          rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
          echo cilium install --azure-resource-group "mhsrg-${{ github.event.inputs.labName }}"
          cilium version
          cilium install 